name: publish

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        toolchain:
          - stable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust ${{ matrix.toolchain }}
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Run Test
        run: cargo test --verbose --features compression

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        toolchain:
          - stable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust ${{ matrix.toolchain }}
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Run Build
        run: cargo build --verbose --features compression

  publish:
    runs-on: ubuntu-latest

    needs: [test, build]

    steps:
      - name: Publish
        run: echo todo
