name: publish

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Test
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo test --verbose --features compression

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Build
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose --features compression

#  build_and_test:
#    name: Rust project - latest
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        toolchain:
#          - stable
#          - beta
#          - nightly
#    steps:
#      - uses: actions/checkout@v4
#      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
#      - run: cargo build --verbose --features compression
#      - run: cargo test --verbose --features compression